apiVersion: v1
kind: Pod
metadata:
  name: mount-nfs
  namespace: default
spec:
  containers:
  - name: mount-nfs
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/

  volumes: 
  - name: html
    nfs:
      path: /volumes
      server: master
