apiVersion: v1
kind: Pod
metadata:
  name: mount
  namespace: default
  labels:
    app: mount
    tier: frontend
  annotations:
    lcs.top/created-by: "cluster admin"
spec:
  containers:
  - name: mount
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80

    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    - name: timezone
      mountPath: /etc/localtime

  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent

    volumeMounts:
    - name: html
      mountPath: /data/
    - name: timezone
      mountPath: /etc/localtime
    #env:
    #- name: TZ
    #  value: "Asia/Shanghai"
    command: ["/bin/sh"]
    args: ["-c","while true; do echo $(date)>>/data/index.html;sleep 2;done"]

  volumes:
  - name: html
    emptyDir: {}
  - name: timezone
    hostPath: 
      path: /usr/share/zoneinfo/Asia/Shanghai
      #type: DirectoryOrCreate
