apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: default
spec:
  # 来自同一个客户端的请求始终发给同一个后端Pod
  selector:
    app: myapp
    release: canary
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
