apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
    role: logstore
  #clusterIP: 99.99.99.99
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
