apiVersion: v1
kind: Pod
metadata:
  name: pod-cm1
  namespace: default
  labels:
    app: pod-cm1
    tier: frontend
spec:
  containers:
    - name: pod-cm1
      image: ikubernetes/myapp:v1
      ports:
      - name: http
        containerPort: 80
      env:
      - name: NGINX_SERVER_NAME
        valueFrom: 
          configMapKeyRef:
            name: nginx-config
            key: server_name
      - name: NGINX_SERVER_PORT
        valueFrom: 
          configMapKeyRef:
            name: nginx-config
            key: server_port
